<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Template;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        Template::truncate();

        $templates = [
            ['name'=>'Hotspot Premium','slug'=>'hotspot-premium','category'=>'modern','short_desc'=>'Template premium dengan desain modern dan elegan, cocok untuk kafe dan restoran.','long_desc'=>'Hotspot Premium adalah template login hotspot dengan desain modern dan profesional. Dirancang khusus untuk kafe, restoran, dan bisnis F&B.','price'=>49000,'badge'=>'Best Seller','features'=>json_encode(['Desain Modern','Responsive','Mudah Dipasang','Login Voucher','Login User/Pass','Timer Countdown','Background Slider']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-blue-500 to-cyan-400','bg-gradient-to-br from-blue-600 to-blue-400','bg-gradient-to-br from-cyan-500 to-teal-400']),'sold_count'=>234,'rating'=>4.9],
            ['name'=>'Hotspot Classic','slug'=>'hotspot-classic','category'=>'classic','short_desc'=>'Desain klasik yang bersih dan ringan, loading cepat di semua perangkat.','long_desc'=>'Hotspot Classic menghadirkan desain bersih dan profesional yang tidak pernah ketinggalan zaman. Template ini sangat ringan dengan ukuran file kecil.','price'=>39000,'badge'=>null,'features'=>json_encode(['Clean Design','Ringan','Support Radius','Login Voucher','Responsive']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-slate-600 to-slate-400']),'sold_count'=>189,'rating'=>4.7],
            ['name'=>'Hotspot Dark','slug'=>'hotspot-dark','category'=>'modern','short_desc'=>'Template dark mode dengan animasi keren, mendukung multi bahasa.','long_desc'=>'Hotspot Dark adalah template premium dengan tema gelap yang elegan. Dilengkapi animasi modern dan dukungan multi bahasa.','price'=>59000,'badge'=>'Baru','features'=>json_encode(['Dark Mode','Animasi Keren','Multi Bahasa','Login Voucher']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-gray-900 to-gray-700']),'sold_count'=>67,'rating'=>4.8],
            ['name'=>'Hotspot Minimalis','slug'=>'hotspot-minimalis','category'=>'minimalis','short_desc'=>'Desain minimalis dengan fokus pada kecepatan dan kemudahan penggunaan.','long_desc'=>'Pilihan tepat bagi yang menginginkan tampilan bersih tanpa banyak elemen visual.','price'=>29000,'badge'=>null,'features'=>json_encode(['Minimalis','Cepat Load','SEO Friendly','Login Voucher','Clean Code']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-emerald-500 to-teal-400']),'sold_count'=>312,'rating'=>4.6],
            ['name'=>'Hotspot Kafe','slug'=>'hotspot-kafe','category'=>'modern','short_desc'=>'Template lengkap untuk kafe dengan sistem voucher dan timer otomatis.','long_desc'=>'Dirancang khusus untuk pemilik kafe. Dilengkapi timer, voucher, dan background video.','price'=>69000,'badge'=>'Populer','features'=>json_encode(['Voucher Ready','Login & Register','Timer Hitung Mundur','Background Video','Menu Hotspot']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-orange-500 to-amber-400']),'sold_count'=>178,'rating'=>4.9],
            ['name'=>'Hotspot Pro','slug'=>'hotspot-pro','category'=>'pro','short_desc'=>'Paket profesional dengan dashboard admin lengkap dan support prioritas.','long_desc'=>'Solusi all-in-one untuk bisnis serius. Dashboard admin, API, custom branding, support 24/7.','price'=>99000,'badge'=>null,'features'=>json_encode(['Full Fitur','Dashboard Admin','Unlimited Support','API Ready','Custom Branding']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-purple-600 to-pink-500']),'sold_count'=>89,'rating'=>5.0],
            ['name'=>'Hotspot Nature','slug'=>'hotspot-nature','category'=>'minimalis','short_desc'=>'Tema alam yang segar, cocok untuk resort, villa, dan hotel.','long_desc'=>'Nuansa alam yang segar dan menenangkan. Cocok untuk resort, villa, dan glamping.','price'=>45000,'badge'=>null,'features'=>json_encode(['Natural Theme','Eco Look','Responsive','Login Voucher']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-green-600 to-emerald-400']),'sold_count'=>145,'rating'=>4.5],
            ['name'=>'Hotspot Corporate','slug'=>'hotspot-corporate','category'=>'pro','short_desc'=>'Desain corporate profesional untuk kantor dan gedung perkantoran.','long_desc'=>'Template enterprise-grade. White label, SSO, GDPR compliance, audit log.','price'=>89000,'badge'=>null,'features'=>json_encode(['Corporate Style','GDPR Ready','White Label','Login SSO','Audit Log']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-blue-900 to-indigo-700']),'sold_count'=>123,'rating'=>4.8],
            ['name'=>'Hotspot Retro','slug'=>'hotspot-retro','category'=>'classic','short_desc'=>'Desain retro unik yang membuat hotspot Anda berbeda dari yang lain.','long_desc'=>'Template bold dan colorful ala era 80-an. Untuk bisnis yang ingin tampil beda.','price'=>35000,'badge'=>'Sale','features'=>json_encode(['Retro Vibes','Unik','Standout Design','Login Voucher']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-red-700 to-yellow-600']),'sold_count'=>56,'rating'=>4.4],
            ['name'=>'Hotspot Gaming','slug'=>'hotspot-gaming','category'=>'modern','short_desc'=>'Tema gaming dengan efek RGB, cocok untuk game center dan esports cafe.','long_desc'=>'Template ultimate untuk game center. Efek RGB, leaderboard, Discord, Twitch.','price'=>79000,'badge'=>null,'features'=>json_encode(['Gaming Theme','RGB Effect','Leaderboard','Discord Link','Twitch Embed']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-violet-700 to-fuchsia-600']),'sold_count'=>201,'rating'=>4.7],
            ['name'=>'Hotspot Medical','slug'=>'hotspot-medical','category'=>'pro','short_desc'=>'Desain bersih dan profesional untuk klinik, rumah sakit, dan apotek.','long_desc'=>'Didesain untuk fasilitas kesehatan. Aksesibilitas tinggi, WCAG compliant.','price'=>69000,'badge'=>null,'features'=>json_encode(['Medical Theme','Accessibility','HIPAA Ready','Patient Portal']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-cyan-600 to-blue-500']),'sold_count'=>78,'rating'=>4.6],
            ['name'=>'Hotspot Ramadan','slug'=>'hotspot-ramadan','category'=>'classic','short_desc'=>'Template spesial Ramadan dengan jadwal sholat terintegrasi.','long_desc'=>'Template spesial bulan Ramadan. Jadwal sholat, countdown iftar, doa harian.','price'=>49000,'badge'=>'Seasonal','features'=>json_encode(['Islamic Theme','Jadwal Sholat','Ramadan Vibes','Countdown Iftar']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-amber-600 to-amber-300']),'sold_count'=>312,'rating'=>4.8],
            ['name'=>'Hotspot Sekolah','slug'=>'hotspot-sekolah','category'=>'minimalis','short_desc'=>'Template edukasi untuk sekolah dan kampus dengan fitur manajemen.','long_desc'=>'Dirancang untuk institusi pendidikan. Filter konten, login NISN, bandwidth control.','price'=>35000,'badge'=>null,'features'=>json_encode(['Edu Theme','Filter Konten','Bandwidth Control','Login NISN']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-sky-500 to-blue-400']),'sold_count'=>167,'rating'=>4.5],
            ['name'=>'Hotspot Hotel','slug'=>'hotspot-hotel','category'=>'pro','short_desc'=>'Template premium hotel dengan login nomor kamar dan billing system.','long_desc'=>'Solusi lengkap perhotelan. Login nomor kamar, billing system, 5 bahasa.','price'=>85000,'badge'=>null,'features'=>json_encode(['Hotel Grade','Room Number Login','Multi Language','Billing System']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-rose-700 to-rose-400']),'sold_count'=>94,'rating'=>4.9],
            ['name'=>'Hotspot Neon','slug'=>'hotspot-neon','category'=>'modern','short_desc'=>'Desain neon glow yang mencolok, cocok untuk bar dan nightclub.','long_desc'=>'Efek neon glow dengan animasi dan particle effect. Untuk bar dan nightclub.','price'=>55000,'badge'=>'Trending','features'=>json_encode(['Neon Glow','Night Mode','Animated BG','Particle Effect']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-black via-purple-950 to-fuchsia-800']),'sold_count'=>145,'rating'=>4.7],
            ['name'=>'Hotspot Simple','slug'=>'hotspot-simple','category'=>'minimalis','short_desc'=>'Template paling simpel, ringan, dan murah. Cocok untuk pemula.','long_desc'=>'Template paling ringan. Ukuran file di bawah 50KB. Sekali upload langsung jalan.','price'=>19000,'badge'=>null,'features'=>json_encode(['Super Ringan','Basic Login','Cepat Pasang','Login Voucher']),'status'=>'published','preview_gradients'=>json_encode(['bg-gradient-to-br from-gray-100 to-gray-300']),'sold_count'=>423,'rating'=>4.3],
        ];

        foreach ($templates as $t) {
            Template::create($t);
        }

        echo "Seeded " . Template::count() . " templates.\n";
    }
}
